name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Install wasm-pack
        run: cargo install wasm-pack
        
      - name: Build
        run: wasm-pack build --target web
        
      - name: Setup Pages
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          git add -f pkg/
          git commit -m "Initial commit for GitHub Pages"
          git push -f origin gh-pages
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pkg
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "Deploy: ${{ github.event.head_commit.message }}" 